version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    ports:
      - 5180:5180
      - 6180:6180
    labels:
      cluster: test
      service: zero
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero -o 100 --my=zero1:5180 --replicas 3 --idx 1 --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --jaeger.collector=http://jaeger:14268

  alpha1:
    image: dgraph/dgraph:latest
    container_name: alpha1
    working_dir: /data/alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
    ports:
      - 8180:8180
      - 9180:9180
    labels:
      cluster: test
      service: alpha
    command: /gobin/dgraph alpha --my=alpha1:7180 --lru_mb=1024 --zero=zero1:5180 -o 100 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16  --acl_secret_file /dgraph-acl/hmac-secret --acl_access_ttl 3s --acl_cache_ttl 5s --jaeger.collector=http://jaeger:14268

  graphql-init:
    image: dgraph/dgraph:latest
    container_name: graphql-init
    working_dir: /data/graphql
    volumes:
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/dgraph/cmd/graphql
        target: /schema
        read_only: true
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    depends_on:
      - alpha1
    labels:
      cluster: test
    command: /gobin/dgraph graphql init --schema /schema/e2e_test_schema.graphql --alpha alpha1:9180 -v3

  graphql:
    image: dgraph/dgraph:latest
    container_name: graphql
    working_dir: /data/graphql
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 9000:9000
    depends_on:
      - graphql-init
    restart: always
    labels:
      cluster: test
      service: graphql
    command: /gobin/dgraph graphql --alpha alpha1:9180 --jaeger.collector=http://jaeger:14268 --v 3

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    working_dir: /working/jaeger
    environment:
    - SPAN_STORAGE_TYPE=badger
    ports:
    - 14268:14268
    - 16686:16686
    command: --badger.ephemeral=false --badger.directory-key /working/jaeger --badger.directory-value /working/jaeger

