version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: ${GOPATH_LINUX_BIN:-$GOPATH/bin}
        target: /gobin
        read_only: true
      - type: bind
        source: ./cdc_logs
        target: /cdc
    command:
      /gobin/dgraph ${COVERAGE_OUTPUT} alpha --my=alpha1:7080 --zero=zero1:5080 --logtostderr --cdc
      "file=/cdc;" -v=2 --security "whitelist=0.0.0.0/0;"
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - "5080"
      - "6080"
    volumes:
      - type: bind
        source: ${GOPATH_LINUX_BIN:-$GOPATH/bin}
        target: /gobin
        read_only: true
    command:
      /gobin/dgraph  ${COVERAGE_OUTPUT} zero --telemetry "reports=false;" --my=zero1:5080
      --logtostderr -v=2 --bindall
volumes: {}
