version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: ./cdc_logs
        target: /cdc
    command: dgraph alpha --my=alpha1:7080 --zero=zero1:5080 --logtostderr
      --cdc "file=/cdc;" -v=2
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - "5080"
      - "6080"
    command: dgraph zero --my=zero1:5080 --logtostderr -v=2 --bindall
volumes: {}
