[build]
  base = "wiki/"
  command = "./scripts/build.sh"
  publish = "./public"
  ignore = "git diff --quiet HEAD^ HEAD ."

[context.production.environment]
  HUGO_VERSION = "0.74.3"
  LOOP = "false"
  HOST = "/"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"
  LOOP = "false"
  HOST = "/"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.74.3"
  LOOP = "false"
  HOST = "/"