version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    ports:
      - 5080
      - 6080
    labels:
      cluster: test
      service: zero1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command:
      /gobin/dgraph  ${COVERAGE_OUTPUT} zero --telemetry "reports=false;" --logtostderr -v=2
      --bindall --profile_mode block --block_rate 10 --my=zero1:5080

  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 8080
      - 9080
    labels:
      cluster: test
      service: alpha1
    command:
      /gobin/dgraph  ${COVERAGE_OUTPUT} alpha --zero=zero1:5080 --profile_mode block
      --block_rate 10 --logtostderr -v=2 --my=alpha1:7080 --security "whitelist=0.0.0.0/0;"
      --graphql "lambda-url=http://lambda:8686/graphql-worker; debug=true;" --trace "ratio=1.0;"

  lambda:
    image: dgraph/dgraph-lambda:latest
    labels:
      cluster: test
    ports:
      - 8686
    depends_on:
      - alpha1
    environment:
      DGRAPH_URL: http://alpha1:8080
    volumes:
      - type: bind
        source: ./script.js
        target: /app/script/script.js
        read_only: true
