baseurl = "http://localhost:1313/"
languageCode = "en-us"
theme = "hugo-docs"

# set by build script: title, baseurl
title = "Dgraph Documentation"

[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "home"
  weight = -1
[[menu.main]]
  name = "Get Started"
  url = "/get-started/"
  identifier = "get-started"
  weight = 1
[[menu.main]]
  name = "Query Language"
  url = "/query-language/"
  identifier = "query-language"
  weight = 3
[[menu.main]]
  name = "Clients"
  url = "/clients/"
  identifier = "clients"
  weight = 4
[[menu.main]]
  name = "Deploy"
  url = "/deploy/"
  identifier = "deploy"
  weight = 5
[[menu.main]]
  name = "FAQ"
  url = "/faq/"
  identifier = "faq"
  weight = 6
[[menu.main]]
  name = "Performance"
  url = "/performance/"
  identifier = "performance"
  weight = 7
[[menu.main]]
  name = "Design Concepts"
  url = "/design-concepts/"
  identifier = "design-concepts"
  weight = 8
[[menu.main]]
  name = "Dgraph Compared to Other Databases"
  url = "/dgraph-compared-to-other-databases/"
  identifier = "dgraph-compared-to-other-databases"
  weight = 9
