# Docker compose file for testing. Use it with:
# docker-compose up --force-recreate
# This would pick up dgraph binary from $GOPATH.

version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    container_name: acl-dg0.1
    working_dir: /data/dg0.1
    ports:
      - 5280:5280
      - 6280:6280
    command: /gobin/dgraph zero --my=zero1:5280 -o 200 --replicas 3 --idx 1 --bindall --expose_trace --profile_mode block --block_rate 10 --logtostderr -v=2
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true

  dg1:
    image: dgraph/dgraph:latest
    container_name: acl-dg1
    working_dir: /data/dg1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/ee/acl
        target: /dgraph-acl
    ports:
      - 8280:8280
      - 9280:9280
      - 9999:9999
    security_opt:
      - seccomp:unconfined
    command: /gobin/dgraph alpha --my=dg1:7280 --lru_mb=1024 --zero=zero1:5280 -o 200 --expose_trace  --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=3 --hmac_secret_file /dgraph-acl/hmac-secret --enterprise_features



