version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5080
      - 6080
    command: /gobin/dgraph zero --cwd=/data/zero1 --my=zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key
      --bindall --logtostderr -v=0
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../tls/zero1
        target: /dgraph-tls
        read_only: true

  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    env_file:
      - ../../backup.env
    labels:
      cluster: test
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../tls/alpha1
        target: /dgraph-tls
        read_only: true
    ports:
      - 8080
      - 9080
    command: /gobin/dgraph alpha --cwd=/data/alpha1 --my=alpha1:7080 --zero=zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      -v=0 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  alpha2:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha2
    env_file:
      - ../../backup.env
    labels:
      cluster: test
    depends_on:
      - alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../tls/alpha2
        target: /dgraph-tls
        read_only: true
    ports:
      - 8080
      - 9080
    command: /gobin/dgraph alpha --cwd=/data/alpha2 --my=alpha2:7080 --zero=zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha2.crt --tls_key /dgraph-tls/client.alpha2.key
      -v=0 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  alpha3:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha3
    env_file:
      - ../../backup.env
    labels:
      cluster: test
    depends_on:
      - alpha2
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../tls/alpha3
        target: /dgraph-tls
        read_only: true
    ports:
      - 8080
      - 9080
    command: /gobin/dgraph alpha --cwd=/data/alpha3 --my=alpha3:7080 --zero=zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha3.crt --tls_key /dgraph-tls/client.alpha3.key
      -v=0 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  minio:
    image: minio/minio:latest
    env_file:
      - ../../backup.env
    ports:
      - 9001
    labels:
      cluster: test
    command: minio server /data/minio --address :9001
