version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    container_name: zero1
    working_dir: /data/zero1
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero1:5080 --replicas 1 --raft="idx=1;"

  alpha1:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    container_name: alpha1
    working_dir: /data/alpha1
    env_file:
      - minio.env
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha1:7080 --zero=zero1:5080 
      --security "whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1;"

  minio:
    image: minio/minio:${MINIO_VERSION}
    command: gateway azure
    container_name: gateway
    env_file:
      - minio.env
    ports:
      - 9000:9000
