# This supresses warnings about helm2 hook
# Comment this out if using helm2
prometheusOperator:
  createCustomResource: false

nameOverride: dgraph-io
commonLabels:
  prometheus: dgraph-io

alertmanager:
  service:
    labels:
      app: dgraph-io
  alertmanagerSpec:
    replicas: 1
    logLevel: debug
  config:
    global:
      resolve_timeout: 2m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'

prometheus:
  serviceAccount:
    create: true
    name: prometheus-dgraph-io
  prometheusSpec:
    alertingEndpoints:
    - namespace: default
      name: alertmanager-dgraph-io
      port: web
    resources:
      requests:
        memory: 400Mi
    serviceMonitorSelector:
      matchLabels:
        app: dgraph-io
    ruleSelector:
      matchLabels:
        app: dgraph-io
        prometheus: dgraph-io
        role: alert-rules
    enableAdminAPI: false
  additionalServiceMonitors:
    - name: zero-dgraph-io
      additionalLabels:
        app: dgraph-io
        prometheus: dgraph-io
      endpoints:
        - port: http-zero
          path: /debug/prometheus_metrics
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          monitor: zero.dgraph-io
    - name: alpha-dgraph-io
      additionalLabels:
        app: dgraph-io
        prometheus: dgraph-io
      endpoints:
        - port: http-alpha
          path: /debug/prometheus_metrics
      namespaceSelector:
        matchNames:
          - default
      selector:
        matchLabels:
          monitor: alpha.dgraph-io

additionalPrometheusRules:
  - name: prometheus-rules-dgraph-io
    groups:
    - name: ./dgraph-alert.rules
      interval: 30s
      rules:
      - alert: AlphaNotReady
        expr: dgraph_alpha_health_status{job="dgraph-alpha-public"}
          == 0
        for: 3m
        annotations:
          description: '{{ $labels.instance }} for cluster {{ $labels.cluster }} has been
            down for more than 3 minutes.'
          summary: Instance {{ $labels.instance }} down
        labels:
          severity: medium
      - alert: AlphaDead
        expr: dgraph_alpha_health_status{job="dgraph-alpha-public"}
          == 0
        for: 10m
        annotations:
          description: '{{ $labels.instance }} for cluster {{ $labels.cluster }} has been
            down for more than 10 minutes.'
          summary: Instance {{ $labels.instance }} down
        labels:
          severity: high
      - alert: HighPendingQueriesCount
        expr: (sum
          by(instance, cluster) (dgraph_pending_queries_total{job="dgraph-alpha-public"}))
          > 1000
        for: 5m
        annotations:
          description: '{{ $labels.instance }} for cluster {{ $labels.cluster }} has
            a high number of pending quries({{ $value }} in last 5m).'
          summary: Instance {{ $labels.instance }} is experiencing high pending query rates.
        labels:
          severity: medium
      - alert: HighAlphaOpenFDCount
        expr: process_open_fds{job="dgraph-alpha-public"}
          / process_max_fds{job="dgraph-alpha-public"} > 0.75
        for: 10m
        annotations:
          description: 'Too many open file descriptors on alpha instance {{ $labels.instance }}: {{ $value
            }} fraction used.'
          summary: 'Alpha instance {{ $labels.instance }} have too many open file descriptors.'
        labels:
          severity: high
      - alert: HighZeroOpenFDCount
        expr: process_open_fds{job="dgraph-zero-public"}
          / process_max_fds{job="dgraph-zero-public"} > 0.75
        for: 10m
        annotations:
          description: 'Too many open file descriptors on zero instance {{ $labels.instance }}: {{ $value
            }} fraction used.'
          summary: 'Zero instance {{ $labels.instance }} have too many open file descriptors.'
        labels:
          severity: high
      - alert: FollowerBehindTs
        expr: (max
          by(cluster) (dgraph_max_assigned_ts)) - (min by(cluster) (dgraph_max_assigned_ts))
          > 1000
        for: 30s
        annotations:
          description: A follower is behind the leader's latest applied timestamp by {{ $value }}.
        labels:
          severity: medium
