version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    container_name: alpha1
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
    - 8180:8180
    - 9180:9180
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: $GOPATH/src/github.com/dgraph-io/dgraph/tlstest/tls
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 100 --my=alpha1:7180 --lru_mb=1024 --zero=zero1:5080 --logtostderr -v=2 --tls_dir /dgraph-tls --tls_client_auth REQUEST
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
    - 5080:5080
    - 6080:6080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    command: /gobin/dgraph zero -o 0 --idx=1 --my=zero1:5080 --logtostderr
      -v=2 --bindall
volumes: {}
