---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: nfsservers.nfs.rook.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .status.state
    description: NFS Server instance state
    name: State
    type: string
  group: nfs.rook.io
  names:
    kind: NFSServer
    listKind: NFSServerList
    plural: nfsservers
    singular: nfsserver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NFSServer is the Schema for the nfsservers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NFSServerSpec represents the spec of NFS daemon
          properties:
            annotations:
              additionalProperties:
                type: string
              description: The annotations-related configuration to add/set on each
                Pod related object.
              type: object
            exports:
              description: The parameters to configure the NFS export
              items:
                description: ExportsSpec represents the spec of NFS exports
                properties:
                  name:
                    description: Name of the export
                    type: string
                  persistentVolumeClaim:
                    description: PVC from which the NFS daemon gets storage for sharing
                    properties:
                      claimName:
                        description: 'ClaimName is the name of a PersistentVolumeClaim
                          in the same namespace as the pod using this volume. More
                          info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims'
                        type: string
                      readOnly:
                        description: Will force the ReadOnly setting in VolumeMounts.
                          Default false.
                        type: boolean
                    required:
                    - claimName
                    type: object
                  server:
                    description: The NFS server configuration
                    properties:
                      accessMode:
                        description: Reading and Writing permissions on the export
                          Valid values are "ReadOnly", "ReadWrite" and "none"
                        enum:
                        - ReadOnly
                        - ReadWrite
                        - none
                        type: string
                      allowedClients:
                        description: The clients allowed to access the NFS export
                        items:
                          description: AllowedClientsSpec represents the client specs
                            for accessing the NFS export
                          properties:
                            accessMode:
                              description: Reading and Writing permissions for the
                                client to access the NFS export Valid values are "ReadOnly",
                                "ReadWrite" and "none" Gets overridden when ServerSpec.accessMode
                                is specified
                              enum:
                              - ReadOnly
                              - ReadWrite
                              - none
                              type: string
                            clients:
                              description: The clients that can access the share Values
                                can be hostname, ip address, netgroup, CIDR network
                                address, or all
                              items:
                                type: string
                              type: array
                            name:
                              description: Name of the clients group
                              type: string
                            squash:
                              description: Squash options for clients Valid values
                                are "none", "rootid", "root", and "all" Gets overridden
                                when ServerSpec.squash is specified
                              enum:
                              - none
                              - rootid
                              - root
                              - all
                              type: string
                          type: object
                        type: array
                      squash:
                        description: This prevents the root users connected remotely
                          from having root privileges Valid values are "none", "rootid",
                          "root", and "all"
                        enum:
                        - none
                        - rootid
                        - root
                        - all
                        type: string
                    type: object
                type: object
              type: array
            replicas:
              description: Replicas of the NFS daemon
              type: integer
          type: object
        status:
          description: NFSServerStatus defines the observed state of NFSServer
          properties:
            message:
              type: string
            reason:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
