version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - 8080
      - 9080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5080
      - 6080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero --idx=1 --my=zero1:5080 --logtostderr
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key
      -v=2 --bindall
volumes: {}
