apiVersion: v1
name: dgraph
version: 0.0.1
appVersion: 1.0.13
description: Dgraph is a horizontally scalable and distributed graph database, providing ACID transactions, consistent replication and linearizable reads.
keywords:
- dgraph
home: https://dgraph.io/
sources:
- https://github.com/dgraph-io/dgraph
maintainers:
- name: dgraph
  email: contact@dgraph.io
icon: https://dgraph.io/assets/images/logo.png
