version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    ports:
      - 5080
      - 6080
    labels:
      cluster: test
      service: zero1
    command: dgraph zero --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --my=zero1:5080

  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    ports:
      - 8080
      - 9080
    labels:
      cluster: test
      service: alpha1
    command: dgraph alpha --zero=zero1:5080 --expose_trace
      --profile_mode block --block_rate 10 --logtostderr -v=2 --my=alpha1:7080
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
      --graphql "lambda-url=http://lambda:8686/graphql-worker;"
      --trace "ratio=1.0;"

  lambda:
    image: dgraph/dgraph-lambda:latest
    labels:
      cluster: test
    ports:
      - 8686
    depends_on:
      - alpha1
    environment:
      DGRAPH_URL: http://alpha1:8080
    volumes:
      - type: bind
        source: ./script.js
        target: /app/script/script.js
        read_only: true
