version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    ports:
      - 5080
      - 6080
    labels:
      cluster: test
      service: zero1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --my=zero1:5080

  alpha1:
    # TODO(Naman): Change this to dgraph/dgraph once the lambda changes are released.
    image: public.ecr.aws/n1e3y0t3/dgraph-lambda:latest
    working_dir: /data/alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 8080
      - 9080
    labels:
      cluster: test
      service: alpha1
    command: /gobin/dgraph alpha --zero=zero1:5080 --expose_trace
      --profile_mode block --block_rate 10 --logtostderr -v=2 --my=alpha1:7080
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
      --lambda "num=2;"
      --trace "ratio=1.0;"

