version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080
      --logtostderr -v=2 --idx=1 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha2:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha2
    depends_on:
    - alpha1
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    command: /gobin/dgraph alpha --my=alpha2:7080 --zero=zero1:5080
      --logtostderr -v=2 --idx=2 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha3:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha3
    depends_on:
    - alpha2
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    command: /gobin/dgraph alpha --my=alpha3:7080 --zero=zero1:5080
      --logtostderr -v=2 --idx=3 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha4:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha4
    depends_on:
    - alpha3
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    command: /gobin/dgraph alpha --my=alpha4:7080 --zero=zero1:5080
      --logtostderr -v=2 --idx=4 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha5:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha5
    depends_on:
    - alpha4
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    command: /gobin/dgraph alpha --my=alpha5:7080 --zero=zero1:5080
      --logtostderr -v=2 --idx=5 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha6:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha6
    depends_on:
    - alpha5
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup2
      read_only: true
    - type: volume
      source: backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../../tlstest/mtls_internal/tls/alpha1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha --my=alpha6:7080 --zero=zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      --logtostderr -v=2 --idx=6 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  ratel:
    image: dgraph/dgraph:latest
    ports:
    - 8000
    command: dgraph-ratel
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
    - 5080
    - 6080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ../../tlstest/mtls_internal/tls/zero1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph zero --idx=1 --my=zero1:5080 --replicas=3 --logtostderr
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key
      -v=2 --bindall
volumes:
  backup: {}
