version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ../../ee/acl/hmac-secret
      target: /dgraph-acl/hmac-secret
      read_only: true
    - type: bind
      source: ../mtls_internal/tls/alpha1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080 --logtostderr -v=2
      --acl "secret-file=/dgraph-acl/hmac-secret;"
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
      --tls "cacert=/dgraph-tls/ca.crt; node-cert=/dgraph-tls/node.crt; node-key=/dgraph-tls/node.key; internal-port-enabled=true; cert=/dgraph-tls/client.alpha1.crt; key=/dgraph-tls/client.alpha1.key; client-auth=VERIFYIFGIVEN;"
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
    - 5080
    - 6080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ../mtls_internal/tls/zero1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph zero --raft "idx=1;" --my=zero1:5080 --logtostderr -v=2 --bindall
      --tls "cacert=/dgraph-tls/ca.crt; node-cert=/dgraph-tls/node.crt; node-key=/dgraph-tls/node.key; internal-port-enabled=true; cert=/dgraph-tls/client.zero1.crt; key=/dgraph-tls/client.zero1.key;"
volumes: {}
